security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\LoginFormAuthenticator
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/car_ad, roles: [ROLE_MANAGER, ROLE_ADMIN] }
        - { path: ^/car_ad/new, roles: [ROLE_MANAGER, ROLE_ADMIN] }
        - { path: ^/car_ad/edit, roles: [ROLE_MANAGER, ROLE_ADMIN] }
        - { path: ^/admin/user, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

